apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chtetta-volume-pvc
spec:
  storageClassName: my-local-storage
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
